### ISSUE TITLE
Empty call

### ISSUE THREAD

**Issue by worldoptimizer** [bennettfeely/bennett#4]
You are calling scroll(), scrollY() and scrollX() in section defining the listener once… but shouldn't that be a call with a "z" meaning zScroll(), zScrollY() and zScrollX().

**Comment by bennettfeely** [comment]
Thanks! Fixed at its own repo.

https://github.com/bennettfeely/ztext/commit/df18a2ed6ae63183cec413bcfba9988bbea4cd8d
