### ISSUE TITLE
[ZText] Vue wrapper

### ISSUE THREAD

**Issue by Namchee** [bennettfeely/bennett#5]
**This is not an issue**

Hi, I was inspired by #3 to create a custom declarative vue ztext component. You can start using it in your projects by installing it from [here](https://www.npmjs.com/package/@namchee/vue-ztext).

Here's the [repository](https://github.com/Namchee/vue-ztext) if you want to contribute anything.

PS: I've done slight modifications on the original code. I believe that I'm allowed to do so according to the license, but if what I'm doing is illegal, please send me an email.

**Comment by bennettfeely** [comment]
Hi! I'm so sorry for the delay but I'm just seeing this now. I'd love to link it to the ztext homepage for more people to see.

**Comment by Namchee** [comment]
@bennettfeely sure. But I don't have any experience with slim template, could you please add a quick start guide for collaboration?
